### ISSUE TITLE
Add Firo Solutions to list

### ISSUE THREAD

**Issue by flipchan** [omarabid/rust-companies#6]
Hey,
The company i work for [Firo Solutions](https://firosolutions.com) is using rust in production, we even have a Cargo.toml scanner at rust.firosolutions.com

Nice list btw!

**Comment by omarabid** [comment]
You can edit the Readme file and make a pull request. I'll merge it.

**Comment by flipchan** [comment]
@omarabid https://github.com/omarabid/rust-companies/pull/8
